version: '3.8'
services:
  # Infraestrutura
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes: ["./prometheus.yml:/etc/prometheus/prometheus.yml"]

  # Serviços Monitorados
  nginx:
    image: nginx/nginx-prometheus-exporter
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "8080:80"    # Porta do NGINX
      - "9113:9113"  # Porta das métricas
    environment:
      NGINX_PORT: 80

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: senha_do_db

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://usuário_do_db:$senha_do_db@postgres:5432/nome_do_db?sslmode=disable"
    depends_on: ["postgres"]

  stress:
    image: alexeiled/stress-ng:latest
    command: ["--cpu", "4", "--vm", "2"]

  # Exportadores
  node_exporter:
    image: prom/node-exporter
    ports: ["9100:9100"]