apiVersion: apps/v1            # Versão da API para aplicações (Deployments)
kind: Deployment               # Tipo: SISTEMA DE PLANTIO INTELIGENTE
metadata:                      # Metadados do sistema de plantio
  name: prometheus-deployment  # Nome do sistema de plantio
  labels:                      # Etiquetas do sistema
    app: prometheus
    tier: monitoring
spec:                          # Como o sistema deve funcionar
  replicas: 4                  # QUANTIDADE DE VASOS: sempre tenha 4 vasos idênticos
  selector:                    # Como encontrar os vasos que este sistema gerencia
    matchLabels:               # Procure vasos com estas etiquetas:
      app: prometheus          # "Todos os vasos marcados como prometheus"
  template:                    # MODELO/MOLDE para criar novos vasos
    metadata:                  # Metadados dos vasos que serão criados
      labels:                  # Etiquetas que cada vaso receberá
        app: prometheus        # "Todo vaso criado terá esta etiqueta"
    spec:                      # Especificação IDÊNTICA ao Pod
      containers:              # ( mesma configuração do Pod anterior )
      - name: prometheus-container
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"