pipeline {
    agent any
    
    environment {
        TF_TOKEN_app_terraform_io = credentials('tf-token-terraform-cloud')
        TF_VAR_ENVIRONMENT = "${params.ENVIRONMENT}"
        WORKSPACE_DIR = "01-iac-railways/${params.TOOL}/${params.CLOUD}"
    }
    
    parameters {
        choice(name: 'TOOL', choices: ['terraform', 'opentofu'], description: 'Qual Ferramenta?')
        choice(name: 'CLOUD', choices: ['aws', 'azure', 'gcp', 'oci'], description: 'Qual Cloud?')
        choice(name: 'ENVIRONMENT', choices: ['dev', 'staging', 'prod'], description: 'Qual Ambiente?')
        choice(name: 'ACTION', choices: ['deploy', 'destroy'], description: 'O que voce quer fazer?')
    }
    
    stages {
        
        // Prepare
        stage('Prepare') {
            steps {
                script {
                    if (params.TOOL == 'terraform') {
                        env.IAC_CMD = 'terraform'
                        def wsMap = [aws: 'dev_aws_tfc', azure: 'dev_azure_tfc', gcp: 'dev_gcp_tfc', oci: 'dev_oci_tfc']
                        if (params.ENVIRONMENT != 'dev') { wsMap[params.CLOUD] = wsMap[params.CLOUD].replace('dev', params.ENVIRONMENT) }
                        env.TF_WORKSPACE = wsMap[params.CLOUD]
                    } else {
                        env.IAC_CMD = 'tofu'
                        def wsMap = [aws: 'dev_aws_tofu', azure: 'dev_azure_tofu', gcp: 'dev_gcp_tofu', oci: 'dev_oci_tofu']
                        if (params.ENVIRONMENT != 'dev') { wsMap[params.CLOUD] = wsMap[params.CLOUD].replace('dev', params.ENVIRONMENT) }
                        env.TF_WORKSPACE = wsMap[params.CLOUD]
                    }
                }
            }
        }
        
        // Validate & SAST
        stage('Validate & SAST') {
            when { expression { params.ACTION == 'deploy' } }
            steps {
                dir("${WORKSPACE_DIR}") {
                    sh '${IAC_CMD} fmt -recursive'
                    sh '${IAC_CMD} init -backend=false'
                    sh '${IAC_CMD} validate'
                    sh 'tfsec .'
                }
            }
        }
        
        // Plan
        stage('Plan') {
            when { expression { params.ACTION == 'deploy' } }
            steps {
                dir("${WORKSPACE_DIR}") {
                    sh '${IAC_CMD} init'
                    sh '${IAC_CMD} plan'
                }
            }
        }
        
        // Apply (GMUD)
        stage('Apply (GMUD)') {
            when { expression { params.ACTION == 'deploy' } }
            steps {
                input message: "Deseja aplicar o deploy no ambiente ${params.ENVIRONMENT}?", ok: "Aplicar"
                dir("${WORKSPACE_DIR}") {
                    sh '${IAC_CMD} apply -auto-approve'
                }
            }
        }
        
        // Destroy
        stage('Destroy') {
            when { expression { params.ACTION == 'destroy' } }
            steps {
                dir("${WORKSPACE_DIR}") {
                    sh '${IAC_CMD} init'
                    sh '${IAC_CMD} destroy -auto-approve'
                }
            }
        }
    }
}