name: OpenTofu Azure OIDC

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init
        working-directory: 01-iac-railways/opentofu/teste/azure

      - name: Tofu Plan
        run: tofu plan -input=false -no-color
        working-directory: 01-iac-railways/opentofu/teste/azure
        env:
          TF_VAR_location_primary: ${{ vars.ARM_PRIMARY_REGION }}
          TF_VAR_location_secondary: ${{ vars.ARM_SECONDARY_REGION }}

     # - name: Tofu Apply
     #   if: github.ref == 'refs/heads/main'
     #   run: tofu apply -auto-approve -input=false
     #   working-directory: 01-iac-railways/opentofu/teste/azure
     #   env:
     #     TF_VAR_location_primary: ${{ vars.AZURE_LOCATION_PRIMARY }}
     #     TF_VAR_location_secondary: ${{ vars.AZURE_LOCATION_SECONDARY }}