name: OpenTofu Deploy AWS (OIDC)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_RUN_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION_PRIMARY }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        run: tofu init
        working-directory: 01-iac-railways/opentofu/teste/aws

      - name: OpenTofu Plan
        env:
          TF_VAR_AWS_REGION_PRIMARY: ${{ vars.AWS_REGION_PRIMARY }}
          TF_VAR_AWS_REGION_SECONDARY: ${{ vars.AWS_REGION_SECONDARY }}
          # Adicione aqui quaisquer outras variáveis que seu código use
        run: tofu plan -input=false -no-color
        working-directory: 01-iac-railways/opentofu/teste/aws

      # - name: OpenTofu Apply
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     TF_VAR_AWS_REGION_PRIMARY: ${{ vars.AWS_REGION_PRIMARY }}
      #     TF_VAR_AWS_REGION_SECONDARY: ${{ vars.AWS_REGION_SECONDARY }}
      #   run: tofu apply -auto-approve -input=false
      #   working-directory: 01-iac-railways/opentofu/teste/aws