name: OpenTofu Azure OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.ARM_CLIENT_ID }}
          tenant-id: ${{ vars.ARM_TENANT_ID }}
          subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}

      - uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init
        working-directory: 01-iac-railways/opentofu/azure

      - name: Tofu Plan
        env:
          TF_VAR_ARM_PRIMARY_REGION: ${{ vars.ARM_PRIMARY_REGION }}
          TF_VAR_ARM_SECONDARY_REGION: ${{ vars.ARM_SECONDARY_REGION }}
        run: tofu plan -input=false -no-color
        working-directory: 01-iac-railways/opentofu/azure

     # - name: Tofu Apply
     #   if: github.ref == 'refs/heads/main'
     #   env:
     #    TF_VAR_ARM_PRIMARY_REGION: ${{ vars.ARM_PRIMARY_REGION }}
     #    TF_VAR_ARM_SECONDARY_REGION: ${{ vars.ARM_SECONDARY_REGION }}
     #   run: tofu apply -auto-approve -input=false
     #   working-directory: 01-iac-railways/opentofu/azure