name: IaC Master Pipeline (Multi-Cloud & Multi-Tool)

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Qual Cloud?'
        required: true
        type: choice
        options:
          - aws
          - azure
          - gcp
      tool:
        description: 'Qual Ferramenta?'
        required: true
        type: choice
        options:
          - terraform
          - opentofu
      environment:
        description: 'Qual Ambiente?'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'O que voce quer fazer?'
        required: true
        type: choice
        options:
          - deploy
          - destroy

jobs:
  # Validate
  validate:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/${{ github.event.inputs.tool }}/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AWS_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AWS }}
      AZURE_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      AZURE_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AZURE }}
      GCP_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
      GCP_TOFU: ${{ vars.TF_WORKSPACE_TOFU_GCP }}
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Terraform
        if: ${{ github.event.inputs.tool == 'terraform' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Configurar OpenTofu
        if: ${{ github.event.inputs.tool == 'opentofu' }}
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.12.6
      - name: Set Dynamic Variables
        run: |
          if [ "${{ github.event.inputs.tool }}" == "terraform" ]; then
            echo "IAC_CMD=terraform" >> $GITHUB_ENV
            echo "TOOL_SHORT=TERRAFORM" >> $GITHUB_ENV
          else
            echo "IAC_CMD=tofu" >> $GITHUB_ENV
            echo "TOOL_SHORT=TOFU" >> $GITHUB_ENV
          fi
          CLOUD_UPPER=$(echo "${{ github.event.inputs.cloud }}" | tr '[:lower:]' '[:upper:]')
          VAR_NAME="${CLOUD_UPPER}_${TOOL_SHORT}"
          echo "TF_WORKSPACE=${!VAR_NAME}" >> $GITHUB_ENV
      - name: Init
        run: $IAC_CMD init
      - name: Validate
        run: $IAC_CMD validate

  # Plan
  plan:
    needs: validate
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/${{ github.event.inputs.tool }}/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AWS_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AWS }}
      AZURE_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      AZURE_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AZURE }}
      GCP_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
      GCP_TOFU: ${{ vars.TF_WORKSPACE_TOFU_GCP }}
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Terraform
        if: ${{ github.event.inputs.tool == 'terraform' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Configurar OpenTofu
        if: ${{ github.event.inputs.tool == 'opentofu' }}
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.12.6
      - name: Set Dynamic Variables
        run: |
          if [ "${{ github.event.inputs.tool }}" == "terraform" ]; then
            echo "IAC_CMD=terraform" >> $GITHUB_ENV
            echo "TOOL_SHORT=TERRAFORM" >> $GITHUB_ENV
          else
            echo "IAC_CMD=tofu" >> $GITHUB_ENV
            echo "TOOL_SHORT=TOFU" >> $GITHUB_ENV
          fi
          CLOUD_UPPER=$(echo "${{ github.event.inputs.cloud }}" | tr '[:lower:]' '[:upper:]')
          VAR_NAME="${CLOUD_UPPER}_${TOOL_SHORT}"
          echo "TF_WORKSPACE=${!VAR_NAME}" >> $GITHUB_ENV
      - name: Init
        run: $IAC_CMD init
      - name: Plan
        run: $IAC_CMD plan

  # Apply
  apply:
    needs: plan
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/${{ github.event.inputs.tool }}/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AWS_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AWS }}
      AZURE_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      AZURE_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AZURE }}
      GCP_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
      GCP_TOFU: ${{ vars.TF_WORKSPACE_TOFU_GCP }}
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Terraform
        if: ${{ github.event.inputs.tool == 'terraform' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Configurar OpenTofu
        if: ${{ github.event.inputs.tool == 'opentofu' }}
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.12.6
      - name: Set Dynamic Variables
        run: |
          if [ "${{ github.event.inputs.tool }}" == "terraform" ]; then
            echo "IAC_CMD=terraform" >> $GITHUB_ENV
            echo "TOOL_SHORT=TERRAFORM" >> $GITHUB_ENV
          else
            echo "IAC_CMD=tofu" >> $GITHUB_ENV
            echo "TOOL_SHORT=TOFU" >> $GITHUB_ENV
          fi
          CLOUD_UPPER=$(echo "${{ github.event.inputs.cloud }}" | tr '[:lower:]' '[:upper:]')
          VAR_NAME="${CLOUD_UPPER}_${TOOL_SHORT}"
          echo "TF_WORKSPACE=${!VAR_NAME}" >> $GITHUB_ENV
      - name: Init
        run: $IAC_CMD init
      - name: Apply
        run: $IAC_CMD apply -auto-approve

  # Destroy
  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/${{ github.event.inputs.tool }}/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AWS_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AWS }}
      AZURE_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      AZURE_TOFU: ${{ vars.TF_WORKSPACE_TOFU_AZURE }}
      GCP_TERRAFORM: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
      GCP_TOFU: ${{ vars.TF_WORKSPACE_TOFU_GCP }}
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Terraform
        if: ${{ github.event.inputs.tool == 'terraform' }}
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Configurar OpenTofu
        if: ${{ github.event.inputs.tool == 'opentofu' }}
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.12.6
      - name: Set Dynamic Variables
        run: |
          if [ "${{ github.event.inputs.tool }}" == "terraform" ]; then
            echo "IAC_CMD=terraform" >> $GITHUB_ENV
            echo "TOOL_SHORT=TERRAFORM" >> $GITHUB_ENV
          else
            echo "IAC_CMD=tofu" >> $GITHUB_ENV
            echo "TOOL_SHORT=TOFU" >> $GITHUB_ENV
          fi
          CLOUD_UPPER=$(echo "${{ github.event.inputs.cloud }}" | tr '[:lower:]' '[:upper:]')
          VAR_NAME="${CLOUD_UPPER}_${TOOL_SHORT}"          
          echo "TF_WORKSPACE=${!VAR_NAME}" >> $GITHUB_ENV
      - name: Init
        run: $IAC_CMD init
      - name: Destroy
        run: $IAC_CMD destroy -auto-approve