name: Terraform Pipeline (AWS)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Qual ambiente fazer deploy?'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  # Job 1: Valida o código (Roda automático)
  validate:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/aws
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          TF_WORKSPACE: ${{ vars.TF_WORKSPACE_AWS }}
      - name: Terraform Validate
        run: terraform validate

  # Job 2: Roda o Plano (Roda automático logo após o validate)
  plan:
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/aws
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          TF_WORKSPACE: ${{ vars.TF_WORKSPACE_AWS }}
      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}

  # Job 3: Deploy (Pausa esperando clique de aprovação)
  apply:
    needs: plan
    runs-on: ubuntu-latest
    # O GitHub vai pausar aqui se o Environment tiver "Required reviewers" marcado
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/aws
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Terraform Init
        run: terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          TF_WORKSPACE: ${{ vars.TF_WORKSPACE_AWS }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment: ${{ github.event.inputs.environment }}