name: Terraform Master Pipeline (Multi-Cloud)

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: 'Qual Cloud?'
        required: true
        type: choice
        options:
          - aws
          - azure
          - gcp
      environment:
        description: 'Qual Ambiente?'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'O que voce quer fazer?'
        required: true
        type: choice
        options:
          - deploy
          - destroy

jobs:
  # Validate
  validate:
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AZURE_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      GCP_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Set Workspace
        run: |
          if [ "${{ github.event.inputs.cloud }}" == "aws" ]; then
            echo "TF_WORKSPACE=$AWS_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "azure" ]; then
            echo "TF_WORKSPACE=$AZURE_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "gcp" ]; then
            echo "TF_WORKSPACE=$GCP_WS" >> $GITHUB_ENV
          fi
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate

  # Plan
  plan:
    needs: validate
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AZURE_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      GCP_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Set Workspace
        run: |
          if [ "${{ github.event.inputs.cloud }}" == "aws" ]; then
            echo "TF_WORKSPACE=$AWS_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "azure" ]; then
            echo "TF_WORKSPACE=$AZURE_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "gcp" ]; then
            echo "TF_WORKSPACE=$GCP_WS" >> $GITHUB_ENV
          fi
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan

  # Apply
  apply:
    needs: plan
    if: ${{ github.event.inputs.action == 'deploy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AZURE_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      GCP_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Set Workspace
        run: |
          if [ "${{ github.event.inputs.cloud }}" == "aws" ]; then
            echo "TF_WORKSPACE=$AWS_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "azure" ]; then
            echo "TF_WORKSPACE=$AZURE_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "gcp" ]; then
            echo "TF_WORKSPACE=$GCP_WS" >> $GITHUB_ENV
          fi
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve

  # Destroy
  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: 01-iac-railways/terraform/${{ github.event.inputs.cloud }}
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      TF_VAR_ENVIRONMENT: ${{ github.event.inputs.environment }}
      AWS_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AWS }}
      AZURE_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_AZURE }}
      GCP_WS: ${{ vars.TF_WORKSPACE_TERRAFORM_GCP }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0
      - name: Set Workspace
        run: |
          if [ "${{ github.event.inputs.cloud }}" == "aws" ]; then
            echo "TF_WORKSPACE=$AWS_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "azure" ]; then
            echo "TF_WORKSPACE=$AZURE_WS" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.cloud }}" == "gcp" ]; then
            echo "TF_WORKSPACE=$GCP_WS" >> $GITHUB_ENV
          fi
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve